### ISSUE TITLE
Error on parsing valid(?) PGN

### ISSUE THREAD

**Issue by slaphead99** [craylton/PgnToFen#1]
Hi - potentially extremely useful library, thank you. I am having trouble parsing this puppy though...
[pasreME.txt](https://github.com/craylton/PgnToFen/files/8992814/pasreME.txt)

**Comment by craylton** [comment]
Hiya, thanks for checking out the library! It was having issues with the `[]` characters in the commentary, as well as the way black's moves are denoted as e.g. `7... dxe4`.
I've pushed an update which should help, let me know how it goes :)

**Comment by craylton** [comment]
Closing this issue as I believe its resolved. Do shout if you still have problems with it.
