### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FauziAkram** [craylton/PgnToFen#2]
Hello @craylton I really need to use your amazing tool (I checked the folder PgnToFenTests and this is exactly what I need)
But I'm not sure exactly how to use it.
When I use CMD and navigate to the folder of your tool, and I enter the command:
PgnToFen.exe --pgnfile MyPgnFile.pgn --output MyFenFile.txt
It gives me the following error:
'PgnToFen.exe' is not recognized as an internal or external command, operable program or batch file.

I'm sorry for my ignorance in the field, can you help me please.
If needed you can contact me at my email: fauzi.dabat@hotmail.com

**Comment by craylton** [comment]
Hiya, no problem at all! You need the source to be compiled into a .exe before running it. I've just uploaded a release containing an exe, fancy trying that out?
https://github.com/craylton/PgnToFen/releases/tag/1

**Comment by FauziAkram** [comment]
Thank you!!
Worked perfectly

**Comment by craylton** [comment]
Brilliant, glad to hear it 😄
